// eslint-disable-next-line filenames/match-exported
import { jaJP } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Noto_Sans_JP as NotoSansJP } from "next/font/google";
import "react-modern-drawer/dist/index.css";
import "ress";
import Layout from "./_components/Layout";
import "./globals.css";

const notoSansJP = NotoSansJP({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Vmate",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
        <ClerkProvider localization={jaJP}>
          <Layout>{children}</Layout>
        </ClerkProvider>
      </body>
    </html>
  );
}
