// eslint-disable-next-line filenames/match-exported
import { jaJP } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "react-modern-drawer/dist/index.css";
import "ress";
import Layout from "./_components/Layout";
import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "ブイメイト",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="ja">
      <body>
        <ClerkProvider localization={jaJP}>
          <Layout>{children}</Layout>
        </ClerkProvider>
      </body>
    </html>
  );
}
